export interface Bookmark {
  title: string
  url: string
  description?: string
  isGitHub?: boolean
}

export const initialBookmarks: Bookmark[] = [
  { title: 'Github - Checkmate', url: 'https://github.com/bluewave-labs/checkmate?tab=readme-ov-file', description: 'Web security vulnerability detection tool' },
  { title: 'Google Cloud Console - Auth Clients', url: 'https://console.cloud.google.com/auth/clients', description: 'Manage OAuth clients and API credentials' },
  { title: 'Gmail API Documentation', url: 'https://apps.make.com/google-email', description: 'Automate email workflows with Gmail integration' },
  { title: 'AI Web Scraping with Google Sheets', url: 'https://us2.make.com/templates/12157-ai-tools-101-ai-web-scraping-with-google-sheets', description: 'Extract data from websites using AI automation' },
  { title: 'Buddy4Study - Scholarship Portal', url: 'https://www.buddy4study.com/scholarship/nsp-top-class-education-scheme-for-sc-students', description: 'Find scholarships and educational opportunities' },
  { title: 'Cursor Rules - Next.js Template', url: 'https://cursor.directory/nextjs-typescript-tailwindcss-supabase-cursor-rules', description: 'AI-optimized Next.js development rules' },
  { title: 'Agentdesk', url: 'https://www.agentdesk.ai/', description: 'AI agent automation for business workflows' },
  { title: 'Framer Site Checklist 2025', url: 'https://checklist.learnframer.site/', description: 'Website optimization and launch checklist' },
  { title: 'Claude Code Templates', url: 'https://aitmpl.com/', description: 'Pre-built code templates for Claude AI' },
  { title: 'OSSU - Computer Science Path', url: 'https://github.com/ossu/computer-science?tab=readme-ov-file#core-programming', description: 'Free self-taught computer science education' },
  { title: 'The Ultimate Guide for Founders - AI-Native Startup', url: 'https://henrythe9th.substack.com/p/14194ed3-f99c-4a26-8737-bee951953823' },
  { title: 'Infographics-AI Generator', url: 'https://infograph.venngage.com/universal-generator' },
  { title: 'Search System - Modern Design', url: 'https://searchsystem.co/' },
  { title: 'Same Energy - Pinterest Alternative', url: 'https://same.energy/' },
  { title: 'Web Interactions Gallery', url: 'https://www.webinteractions.gallery/' },
  { title: 'Vertical Carousel Slideshow - Envato', url: 'https://elements.envato.com/vertical-carousel-slideshow-92FX73P' },
  { title: 'Drkst - Engagement Animation', url: 'https://drkst.framer.website/' },
  { title: 'Photographer Portfolio - Framer Template', url: 'https://photographers.framer.website/?via=realmehedi1' },
  { title: 'Moore - Framer Portfolio Template', url: 'https://john-moore.framer.website/#home' },
  { title: 'Portavia', url: 'https://portavia.framer.website/' },
  { title: 'Refero Styles - Design Examples', url: 'https://styles.refero.design/?q=monochrome+interface' },
  { title: 'Unicorn.studio - WebGL Tool', url: 'https://www.unicorn.studio/' },
  { title: 'Space Type Generator', url: 'https://spacetypegenerator.com/' },
  { title: 'Design Systems Index', url: 'https://rubenferreiraduarte.notion.site/4d6689eec17a46bc84ecfedbd7c85220' },
  { title: 'Visual Electric - AI Image Generator', url: 'https://visualelectric.com/inspo' },
  { title: 'Lovart - Design Agent', url: 'https://www.lovart.ai/canvas' },
  { title: 'Trending Design - Curated Products', url: 'https://trending.design/' },
  { title: 'Khroma - AI Color Tool', url: 'https://www.khroma.co/generator' },
  { title: 'Aura - Beautiful Designs', url: 'https://www.aura.build/' },
  { title: 'Unsplash - 3D Renders', url: 'https://unsplash.com/t/3d-renders' },
  { title: 'The Creative Website Manual', url: 'https://www.creativewebmanual.com/' },
  { title: 'ASC11 - ASCII Art Generator', url: 'https://asc11.com/' },
  { title: 'GetDesign.md - Design Collection', url: 'https://getdesign.md/' },
  { title: 'Motion.dev - Website Animations', url: 'https://motion.dev' },
  { title: 'Bklit - UI for Charts', url: 'https://bklit.com' },
  { title: 'Kokonut UI - Web Components', url: 'https://kokonutui.com' },
  { title: 'PPPixelate - SVG Pixel Art', url: 'https://www.fffuel.co/pppixelate' },
  { title: 'Game Icons - Free SVG Icons', url: 'https://game-icons.net/' },
  { title: 'Charco Design - Illustrations', url: 'https://www.charco.design/design-resources-illustrations' },
  { title: 'Svgl - SVG Logos Library', url: 'https://svgl.app/' },
  { title: 'Free Faces - Font Gallery', url: 'https://www.freefaces.gallery/' },
  { title: 'Fonts In Use', url: 'https://fontsinuse.com/' },
  { title: 'Fontshare - Free Quality Fonts', url: 'https://www.fontshare.com/' },
  { title: 'All Free Fonts', url: 'https://www.allfreefonts.co/' },
  { title: 'UNCUT.wtf - Fonts', url: 'https://uncut.wtf/' },
  { title: 'Cosmos - Graphic Style Images', url: 'https://www.cosmos.so/' },
  { title: 'Safe Haven HQ - Goth Graphic Designs', url: 'https://www.safehavenhq.com/' },
  { title: 'Ideogram - AI Image Generator', url: 'https://ideogram.ai/t/explore' },
  { title: "People's Graphic Design Archive", url: 'https://peoplesgdarchive.org/' },
  { title: 'The Peculiar Manicule', url: 'https://www.peculiarmanicule.com/' },
  { title: 'GradientGen', url: 'https://noegarsoux.github.io/GradientGen/' },
  { title: 'PixelCrash', url: 'https://www.pixelcrash.xyz/' },
  { title: 'ContentCore - Mockups', url: 'https://contentcore.xyz/' },
  { title: 'Made & Marked Goods', url: 'https://mademarkedgoods.gumroad.com/' },
  { title: 'App Motion - Mobile Design Gallery', url: 'https://appmotion.design/' },
  { title: 'ProductionCrate - VFX Assets', url: 'https://www.productioncrate.com/' },
  { title: 'Software Mansion', url: 'https://swmansion.com/' },
  { title: 'Harvard ML Systems Course', url: 'https://github.com/harvard-edge/cs249r_book' },
  { title: 'Frutiger Aero Archive', url: 'https://frutigeraeroarchive.org/' },
  { title: 'ECC Tools - Claude Code', url: 'https://ecc.tools/#features' },
  { title: 'Agentic AI Design Patterns', url: 'https://docs.google.com/document/d/1rsaK53T3Lg5KoGwvf8ukOUvbELRtH-V0LnOIFDxBryE' },
  { title: 'Jules - Google', url: 'https://jules.google.com/task' },
  { title: 'Ramp Labs - AI Agents', url: 'https://x.com/RampLabs/status/2042660310851449223' },
  { title: 'DESIGN.md Directory', url: 'https://designdotmd.directory/' },
  { title: 'Android Debug Bridge', url: 'https://developer.android.com/tools/adb#move' },
  { title: 'Read.ai - Plans & Pricing', url: 'https://www.read.ai/plans-pricing' },
  { title: 'Mirage AI Video', url: 'https://mirage.app/' },
  { title: 'Kling AI - Creative Studio', url: 'https://www.klingai.com/global/' },
  { title: 'Smart India Hackathon 2025', url: 'https://dev.to/avinash201199/smart-india-hackathon-sih-2025-828' },
  { title: 'Linux Hardening - Pluralsight', url: 'https://www.pluralsight.com/resources/blog/tech-operations/linux-hardening-secure-server-checklist' },
  { title: 'Browserbase MCP Configuration', url: 'https://docs.browserbase.com/integrations/mcp/configuration' },
  { title: 'My Current AI Dev Workflow', url: 'https://steipete.me/posts/2025/optimal-ai-development-workflow' },
  { title: 'Device Info - Security Tool', url: 'https://www.deviceinfo.me/' },
  { title: 'Proton VPN', url: 'https://go.getproton.me/aff_c?offer_id=26&aff_id=1113' },
  { title: 'TunnelBear VPN', url: 'http://www.dpbolvw.net/click-558992-13727132' },
  { title: 'Hide.me VPN', url: 'https://hide.me/?friend=wimia&chan=2' },
  { title: 'Windscribe VPN', url: 'https://windscribe.com/?affid=8eldwz32' },
  { title: 'Privado VPN', url: 'https://privadovpn.com/#a_aid=wimia' },
  { title: 'Floguo - Design Engineering', url: 'https://www.floguo.com/notes/design-engineering' },
  { title: 'Aarav Portfolio', url: 'https://aarav2709.github.io/' },
  { title: 'OmniRouter - AI Providers', url: 'https://omnirouter.com' },
  { title: 'Google ADK Crash Course', url: 'https://codelabs.developers.google.com/onramp' },
  { title: 'Hugging Face - AI Agents Course', url: 'https://huggingface.co/learn/agents-course/en/unit0/introduction' },
  { title: 'LangChain - Deep Agents Course', url: 'https://academy.langchain.com/courses/deep-agents-with-langgraph' },
  { title: 'Stuff I Found', url: 'https://stuffifound.pages.dev/' },
  { title: 'Open Doors - UX Jobs', url: 'https://opendoorscareers.com/jobs' },
  { title: 'Miruro - Anime Streaming', url: 'https://www.miruro.com/' },
  { title: 'Intern Finds - Job Portal', url: 'https://getsig.in/jobs' },
  { title: 'Pixiv - Wuthering Waves Art', url: 'https://www.pixiv.net/en/artworks/133352325' },
];
